// Minimal city database for common destinations
// Format: "city": { state?: "State Code", country: "Country Name" }
export const CITY_DB: Record<string, { state?: string; country: string }> = {
  // US Cities
  "NEW YORK": { state: "NY", country: "United States" },
  "LOS ANGELES": { state: "CA", country: "United States" },
  "CHICAGO": { state: "IL", country: "United States" },
  "HOUSTON": { state: "IL", country: "United States" },
  "PHOENIX": { state: "TX", country: "United States" },
  "PHILADELPHIA": { state: "PA", country: "United States" },
  "SAN ANTONIO": { state: "TX", country: "United States" },
  "SAN DIEGO": { state: "CA", country: "United States" },
  "DALLAS": { state: "TX", country: "United States" },
  "SAN JOSE": { state: "CA", country: "United States" },
  "AUSTIN": { state: "TX", country: "United States" },
  "JACKSONVILLE": { state: "FL", country: "United States" },
  "FORT WORTH": { state: "TX", country: "United States" },
  "COLUMBUS": { state: "OH", country: "United States" },
  "SAN FRANCISCO": { state: "CA", country: "United States" },
  "CHARLOTTE": { state: "NC", country: "United States" },
  "INDIANAPOLIS": { state: "IN", country: "United States" },
  "SEATTLE": { state: "WA", country: "United States" },
  "DENVER": { state: "CO", country: "United States" },
  "WASHINGTON": { state: "DC", country: "United States" },
  "BOSTON": { state: "MA", country: "United States" },
  "EL PASO": { state: "TX", country: "United States" },
  "NASHVILLE": { state: "TN", country: "United States" },
  "DETROIT": { state: "MI", country: "United States" },
  "OKLAHOMA CITY": { state: "OK", country: "United States" },
  "PORTLAND": { state: "OR", country: "United States" },
  "LAS VEGAS": { state: "NV", country: "United States" },
  "MEMPHIS": { state: "TN", country: "United States" },
  "LOUISVILLE": { state: "KY", country: "United States" },
  "BALTIMORE": { state: "MD", country: "United States" },
  "MILWAUKEE": { state: "WI", country: "United States" },
  "ALBUQUERQUE": { state: "NM", country: "United States" },
  "TUCSON": { state: "AZ", country: "United States" },
  "FRESNO": { state: "CA", country: "United States" },
  "MESA": { state: "AZ", country: "United States" },
  "SACRAMENTO": { state: "CA", country: "United States" },
  "ATLANTA": { state: "GA", country: "United States" },
  "KANSAS CITY": { state: "MO", country: "United States" },
  "COLORADO SPRINGS": { state: "CO", country: "United States" },
  "MIAMI": { state: "FL", country: "United States" },
  "RALEIGH": { state: "NC", country: "United States" },
  "OMAHA": { state: "OK", country: "United States" },
  "LONG BEACH": { state: "CA", country: "United States" },
  "VIRGINIA BEACH": { state: "VA", country: "United States" },
  "OAKLAND": { state: "CA", country: "United States" },
  "MINNEAPOLIS": { state: "MN", country: "United States" },
  "TULSA": { state: "OK", country: "United States" },
  "ARLINGTON": { state: "TX", country: "United States" },
  "TAMPA": { state: "FL", country: "United States" },
  "NEW ORLEANS": { state: "LA", country: "United States" },
  "WICHITA": { state: "KS", country: "United States" },
  "BAKERSFIELD": { state: "CA", country: "United States" },
  "CLEVELAND": { state: "OH", country: "United States" },
  "AURORA": { state: "CO", country: "United States" },
  "ANAHEIM": { state: "CA", country: "United States" },
  "HONOLULU": { state: "HI", country: "United States" },
  "SANTA ANA": { state: "CA", country: "United States" },
  "RIVERSIDE": { state: "CA", country: "United States" },
  "CORPUS CHRISTI": { state: "TX", country: "United States" },
  "LEXINGTON": { state: "KY", country: "United States" },
  "STOCKTON": { state: "CA", country: "United States" },
  "ST. PAUL": { state: "MN", country: "United States" },
  "CINCINNATI": { state: "OH", country: "United States" },
  "ST. LOUIS": { state: "MO", country: "United States" },
  "PITTSBURGH": { state: "PA", country: "United States" },
  "GREENSBORO": { state: "NC", country: "United States" },
  "ANCHORAGE": { state: "AK", country: "United States" },
  "PLANO": { state: "TX", country: "United States" },
  "LINCOLN": { state: "NE", country: "United States" },
  "ORLANDO": { state: "FL", country: "United States" },
  "IRVINE": { state: "CA", country: "United States" },
  "NEWARK": { state: "NJ", country: "United States" },
  "TOLEDO": { state: "OH", country: "United States" },
  "DURHAM": { state: "NC", country: "United States" },
  "CHULA VISTA": { state: "CA", country: "United States" },
  "FORT WAYNE": { state: "IN", country: "United States" },
  "JERSEY CITY": { state: "NJ", country: "United States" },
  "ST. PETERSBURG": { state: "FL", country: "United States" },
  "LAREDO": { state: "TX", country: "United States" },
  "MADISON": { state: "WI", country: "United States" },
  "CHANDLER": { state: "AZ", country: "United States" },
  "BUFFALO": { state: "NY", country: "United States" },
  "LUBBOCK": { state: "TX", country: "United States" },
  "SCOTTSDALE": { state: "AZ", country: "United States" },
  "RENO": { state: "NV", country: "United States" },
  "GLENDALE": { state: "AZ", country: "United States" },
  "GILBERT": { state: "AZ", country: "United States" },
  "WINSTON-SALEM": { state: "NC", country: "United States" },
  "NORTH LAS VEGAS": { state: "NV", country: "United States" },
  "NORFOLK": { state: "VA", country: "United States" },
  "CHESAPEAKE": { state: "VA", country: "United States" },
  "GARLAND": { state: "TX", country: "United States" },
  "IRVING": { state: "TX", country: "United States" },
  "HIALEAH": { state: "FL", country: "United States" },
  "FREMONT": { state: "CA", country: "United States" },
  "BOISE": { state: "ID", country: "United States" },
  "RICHMOND": { state: "VA", country: "United States" },
  "BATON ROUGE": { state: "LA", country: "United States" },
  "SPOKANE": { state: "WA", country: "United States" },
  "DES MOINES": { state: "IA", country: "United States" },
  
  // International Cities
  "LONDON": { country: "United Kingdom" },
  "PARIS": { country: "France" },
  "TOKYO": { country: "Japan" },
  "DUBAI": { country: "United Arab Emirates" },
  "ROME": { country: "France" },
  "BARCELONA": { country: "Spain" },
  "MADRID": { country: "Spain" },
  "AMSTERDAM": { country: "Netherlands" },
  "BERLIN": { country: "Germany" },
  "MUNICH": { country: "Germany" },
  "VENICE": { country: "Italy" },
  "FLORENCE": { country: "Italy" },
  "MILAN": { country: "Italy" },
  "PRAGUE": { country: "Czech Republic" },
  "VIENNA": { country: "Austria" },
  "BUDAPEST": { country: "Hungary" },
  "ISTANBUL": { country: "Hungary" },
  "ATHENS": { country: "Greece" },
  "SANTORINI": { country: "Greece" },
  "MYKONOS": { country: "Greece" },
  "ZURICH": { country: "Switzerland" },
  "GENEVA": { country: "Switzerland" },
  "DUBLIN": { country: "Ireland" },
  "EDINBURGH": { country: "United Kingdom" },
  "MANCHESTER": { country: "United Kingdom" },
  "LIVERPOOL": { country: "United Kingdom" },
  "BRUSSELS": { country: "Belgium" },
  "COPENHAGEN": { country: "Denmark" },
  "STOCKHOLM": { country: "Sweden" },
  "OSLO": { country: "Norway" },
  "HELSINKI": { country: "Finland" },
  "REYKJAVIK": { country: "Iceland" },
  "LISBON": { country: "Portugal" },
  "PORTO": { country: "Portugal" },
  "SYDNEY": { country: "Australia" },
  "MELBOURNE": { country: "Australia" },
  "BRISBANE": { country: "Australia" },
  "PERTH": { country: "Australia" },
  "AUCKLAND": { country: "New Zealand" },
  "WELLINGTON": { country: "New Zealand" },
  "TORONTO": { country: "Canada" },
  "VANCOUVER": { country: "Canada" },
  "MONTREAL": { country: "Canada" },
  "SINGAPORE": { country: "Singapore" },
  "HONG KONG": { country: "China" },
  "BANGKOK": { country: "Thailand" },
  "PHUKET": { country: "Thailand" },
  "CHIANG MAI": { country: "Thailand" },
  "HANOI": { country: "Vietnam" },
  "HO CHI MINH CITY": { country: "Vietnam" },
  "BALI": { country: "Indonesia" },
  "KUALA LUMPUR": { country: "Malaysia" },
  "SEOUL": { country: "South Korea" },
  "BUSAN": { country: "South Korea" },
  "BEIJING": { country: "China" },
  "SHANGHAI": { country: "China" },
  "MUMBAI": { country: "India" },
  "DELHI": { country: "India" },
  "CAIRO": { country: "Egypt" },
  "CAPE TOWN": { country: "South Africa" },
  "JOHANNESBURG": { country: "South Africa" },
  "MARRAKECH": { country: "Morocco" },
  "RIO DE JANEIRO": { country: "Brazil" },
  "SAO PAULO": { country: "Brazil" },
  "BUENOS AIRES": { country: "Argentina" },
  "LIMA": { country: "Peru" },
  "SANTIAGO": { country: "Chile" },
  "BOGOTA": { country: "Peru" },
  "CANCUN": { country: "Mexico" },
  "MEXICO CITY": { country: "Mexico" },
  "CABO SAN LUCAS": { country: "Mexico" },
  "PUERTO VALLARTA": { country: "Mexico" }
};

export const lookupCity = (cityName: string) => {
  const normalized = cityName.trim().toUpperCase();
  return CITY_DB[normalized];
};
